# Server Config
spring:
  application:
    name: blockchain-adapter-service

server:
  port: 8084

# MySQL Database
  datasource:
    url: jdbc:mysql://blockchain-db:3306/bicap_blockchain_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Kafka Config
  kafka:
    bootstrap-servers: bicap-kafka:9092
    consumer:
      group-id: blockchain-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # RabbitMQ Config
  rabbitmq:
    host: bicap-message-queue
    port: 5672
    username: root
    password: root

# BICAP RabbitMQ Config
bicap:
  rabbitmq:
    exchange: bicap_exchange
    queue:
      request: farm_request_queue
      response: farm_response_queue
    routing-key:
      request: bicap_routing_key
      response: bicap_routing_key_response

# VeChainThor Config
vechainthor:
  node:
    url: https://mainnet.veblocks.net
    api:
      key: 

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.bicap: DEBUG
