'use client';
import { useEffect,useState } from 'react';import Link from 'next/link';import { orderApi,getErrorMessage } from '@/lib/api';import { useRetailerSession } from '@/lib/marketplace';
interface Order { orderId:number; status:string; totalAmount:number; createdAt?:string; items:{productId:number;productName:string;quantity:number;unitPrice:number}[]; }
const labels:Record<string,string>={CREATED:'Chờ trang trại xác nhận',CONFIRMED:'Trang trại đã xác nhận',REJECTED:'Trang trại từ chối',COMPLETED:'Hoàn thành',CANCELLED:'Đã hủy'};
export default function OrdersPage(){const ready=useRetailerSession();const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [refresh,setRefresh]=useState(0);
  useEffect(()=>{if(!ready)return;let active=true;setLoading(true);orderApi.getMyOrders().then(r=>{if(active){setOrders(r.data);setError(null);}}).catch(err=>{if(active)setError(getErrorMessage(err));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[ready,refresh]);
  return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-5xl space-y-6 px-6 py-8"><Link href="/marketplace" className="text-emerald-700">← Sàn giao dịch</Link><div className="flex justify-between"><h1 className="text-3xl font-bold">Đơn hàng của tôi</h1><button type="button" className="btn-secondary" disabled={loading} onClick={()=>setRefresh(n=>n+1)}>Tải lại</button></div>
    {!ready||loading?<p>Đang tải đơn hàng...</p>:error?<p role="alert" className="text-red-700">{error}</p>:orders.length===0?<p className="rounded-xl bg-white p-8">Chưa có đơn hàng.</p>:orders.map(order=><article key={order.orderId} className="space-y-3 rounded-xl bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="font-bold">Đơn hàng #{order.orderId}</h2><p className="text-emerald-800">{labels[order.status]||order.status}</p></div><p className="text-sm text-slate-500">{order.createdAt?new Date(order.createdAt).toLocaleString('vi-VN'):''}</p>{order.items?.map((item,index)=><p key={index}>{item.productName} · {item.quantity} × {item.unitPrice.toLocaleString('vi-VN')}đ</p>)}<p className="font-bold">Tổng tiền hàng: {order.totalAmount.toLocaleString('vi-VN')}đ</p></article>)}
  </div></main>;
}
